openapi: 3.0.0
info:
  version: 1.0.2
  title: seers
  termsOfService: 'https://seers.io/terms/'
  contact:
    email: admin@mckinleyrice.com
    url: 'http://seers.io/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: ./logo.png
  description: |
    This is an Seers API to demonstrate features of seers API specification

    # Introduction
    This specification is intended to to be a good starting point for describing your API in It also demonstrates features of [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo) tool and 
    [seers-API](https://github.com/mckinley-and-rice/seers-api) documentation engine. So beyond the standard SewersAPI syntax we use a few 
    [vendor extensions](https://github.com/mckinley-and-rice/seers-api/blob/master/docs/redoc-vendor-extensions.md).

    ## Status header response code:
    ### Note
      * 1xx: Informational - Request received, continuing process
      * 2xx: Success - The action was successfully received, understood, and accepted
      * 3xx: Redirection - Further action must be taken in order to complete the request
      * 4xx: Client Error - The request contains bad syntax or cannot be fulfilled
      * 5xx: Server Error - The server failed to fulfill an apparently valid request
    ### Response code:
    * 200 - Success.
    * 201 - Created. Returned on successful creation of a new resource. Includes a 'Location' 
    * 202 – Accepted The client requested to create something on the server. It was accepted, but it has not been completed.
    * 203 – Non-Authoritative Information Information was transmitted, but it was not taken from the primary source.
    * 204 – No Content The request was received, but there was no data sent to the client.
    * 205 – Reset Content  Similar to 204, but the response also includes a request to update the content.
    * 206 – Partial Content Only a portion of the header content was sent to the client.
    * 207 – Multi-Status  The server passed the results of several independent operations at once
    * 301 - The requested resource has been moved permanently.
    * 302 - The requested resource has moved, but was found.
    * 304 - The requested resource has not been modified since the last time you accessed it.
    * 400 - Bad request. Data issues such as invalid JSON, etc.
    * 401 - Unauthorized. Token invalid
    * 404 - Not found. Resource not found on GET.
    * 405 - Method not allowed.
    * 406 - Not acceptable response.
    * 409 - Conflict. Duplicate data or invalid data state would occur.
    * 500 - Internal Server Error
externalDocs:
  description: Find out how to create Github repo for your OpenAPI spec.
  url: 'https://github.com/mckinley-and-rice/seers-api'
tags:
  - name: API Status
    description: Status echo operations for server
  - name: User
    description: Operations about Doctor and Patient user
  - name: Authenticate
    description: All Operations about authentication for ALl users
  - name: Registration
    description: All Operations about authentication for ALl users
  - name: Admin User
    description: Operations about Admin user
  - name: Images
    description: Operations of Patient Images
  - name: Educational Videos
    description: Operations about educational Videos for Patients
  - name: Appointment
    description: Operations about Appointment
  - name: Sample
    description: Operations to make copy for other API
  - name: Echo
    description: Example echo operations
servers:
  - url: 'https://seersapi.mckinleyrice.com/api/v1'
paths:
  /admin':
    parameters:
      - name: Operations of Admin Users
        in: query
        description: status response
        schema:
          $ref: '#/components/schemas/Admin'
    post:
      tags:
        - Admin User
      summary: Create Admin User
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: createAdmin
      security:
        - basic_auth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
              example:
                status: 1
                response: Admin added successfully
        '400':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
              example:
                status: 0
                response: Already an admin account for this email address
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
              example:
                Status: 0
                response: No token provided
        '500':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
              example:
                status: 0
                response: Something went wrong. Please try again
  '/admin/{id}':
    parameters:
      - name: Operations of Admin Users
        in: query
        description: status response
        schema:
          type: string
    delete:
      tags:
        - Admin User
      summary: Delete Admin User
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteAdmin
      parameters:
        - name: id
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
      security:
        - basic_auth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
              example:
                Status: 0
                response: No token provided
    put:
      tags:
        - Admin User
      summary: Update Admin User
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: updateAdmin
      parameters:
        - name: id
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
      security:
        - basic_auth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
              example:
                Status: 0
                response: No token provided
  /appointment:
    parameters:
      - name: Get server health status
        in: query
        description: status response
        schema:
          type: string
    post:
      tags:
        - Appointment
      summary: Create Appointment
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: postAppointment
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
              example:
                Status: 0
                response: No token provided
    get:
      tags:
        - Appointment
      summary: List of Appointment
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getAppointment
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Server Not Working
  '/appointment/{id}':
    parameters:
      - name: Get server health status
        in: query
        description: status response
        schema:
          type: string
    delete:
      tags:
        - Appointment
      summary: Delete Appointment
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteAppointment
      parameters:
        - name: id
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
    put:
      tags:
        - Appointment
      summary: update Appointment
      description: Some description of the operation. You can use `markdown` here.
      operationId: updateAppointment
      parameters:
        - name: id
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '403':
          description: Forbidden
        '404':
          description: Server Not Working
  '/appointment/doctor/{doctorid}':
    parameters:
      - name: Get server health status
        in: query
        description: status response
        schema:
          type: string
    delete:
      tags:
        - Appointment
      summary: Delete Appointment - Doctor id
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteAppointmentdoctorid
      parameters:
        - name: doctorid
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
    put:
      tags:
        - Appointment
      summary: Update Appointment  - Doctor id
      description: Some description of the operation. You can use `markdown` here.
      operationId: updateAppointmentdoctorid
      parameters:
        - name: doctorid
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '403':
          description: Forbidden
        '404':
          description: Server Not Working
    get:
      tags:
        - Appointment
      summary: List of Appointments
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getAppointmentdoctorid
      parameters:
        - name: doctorid
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Server Not Working
  '/appointment/patient/{patientid}':
    parameters:
      - name: Get server health status
        in: query
        description: status response
        schema:
          type: string
    delete:
      tags:
        - Appointment
      summary: Delete Appointment - Patient id
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteAppointmentpatientid
      parameters:
        - name: patientid
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
    put:
      tags:
        - Appointment
      summary: Get server status
      description: Some description of the operation. You can use `markdown` here.
      operationId: updateAppointmentpatientid
      parameters:
        - name: patientid
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '403':
          description: Forbidden
        '404':
          description: Server Not Working
    get:
      tags:
        - Appointment
      summary: List of Appointment
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getAppointmentpatientid
      parameters:
        - name: patientid
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Server Not Working
  /auth/authenticate:
    parameters:
      - name: Get server health status
        in: query
        description: status response
        schema:
          type: string
    post:
      tags:
        - Authenticate
      summary: Authenticate User (Login)
      description: |
        (All type of user) 
      operationId: authAll
      security:
        - basic_auth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                Status: 0
                response: No token provided
  /auth/logout:
    parameters:
      - name: Get server health status
        in: query
        description: status response
        schema:
          type: string
    get:
      tags:
        - Authenticate
      summary: Logout
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: logoutAll
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                Status: 0
                response: No token provided
  /echo:
    post:
      tags:
        - Echo
      summary: Echo test
      description: Receive the exact message you've sent
      operationId: echo
      security:
        - api_key: []
        - basic_auth: []
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              $ref: '#/components/headers/ExpiresAfter'
          content:
            application/json:
              schema:
                type: string
              examples:
                response:
                  value: Hello world!
            application/xml:
              schema:
                type: string
            text/csv:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
              example: Hello world!
          application/xml:
            schema:
              type: string
              example: Hello world!
        description: Echo payload
        required: true
      x-code-samples:
        - lang: 'C#'
          source: |
            API.v1.Echo echo = new API.v1.Echo();
            echo.message = "Hello World!");
            EchoResponse response = echo.post();
            if (response.statusCode == HttpStatusCode.Created)
            {
              // Success
            }
            else
            {
              // Something wrong -- check response for errors
              Console.WriteLine(response.getRawResponse());
            }
        - lang: PHP
          source: |
            $form = new \API\Entities\Echo();
            $form->setMessage("Hello World!");
            try {
                $pet = $client->echo()->post($form);
            } catch (UnprocessableEntityException $e) {
                var_dump($e->getErrors());
            }
  /health:
    parameters:
      - name: Get server health status
        in: query
        description: status response
        schema:
          type: string
    get:
      tags:
        - API Status
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getStatus
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Server Not Working
  /images':
    parameters:
      - name: Operations of Admin Users
        in: query
        description: status response
        schema:
          type: string
    post:
      tags:
        - Images
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: addImages
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
              example:
                Status: 0
                response: No token provided
    get:
      tags:
        - Images
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getimages
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                description: Images
                items:
                  $ref: '#/components/schemas/Image'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
              example:
                Status: 0
                response: No token provided
  /register/doctor:
    parameters:
      - name: Get server health status
        in: query
        description: status response
        schema:
          type: string
    post:
      tags:
        - Registration
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: registerDoctor
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doctor'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doctor'
              example:
                Status: 0
                response: No token provided
  /register/patient:
    parameters:
      - name: Get server health status
        in: query
        description: status response
        schema:
          type: string
    post:
      tags:
        - Registration
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: registerPatient
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
              example:
                Status: 0
                response: No token provided
  /sample:
    parameters:
      - name: Sample Operations
        in: query
        description: status response
        schema:
          type: string
    post:
      tags:
        - Sample
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: postSample
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
              example:
                Status: 0
                response: No token provided
    put:
      tags:
        - Sample
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: putSample
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
              example:
                Status: 0
                response: No token provided
  '/users/{username}':
    parameters:
      - name: pretty_print
        in: query
        description: Pretty print response
        schema:
          type: boolean
    get:
      tags:
        - User
      summary: Get user by user name
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getUserByName
      parameters:
        - name: username
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
        - name: with_email
          in: query
          description: Filter users without email
          schema:
            type: boolean
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                username: user1
                email: user@columbusx.com
        '403':
          description: Forbidden
        '404':
          description: User not found
    put:
      tags:
        - User
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
        - name: username
          in: path
          description: The name that needs to be updated
          required: true
          schema:
            type: string
      security:
        - main_auth:
            - 'write:users'
      responses:
        '200':
          description: OK
        '400':
          description: Invalid user supplied
        '404':
          description: User not found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
        description: Updated user object
        required: true
  /video:
    parameters:
      - name: Get server health status
        in: query
        description: status response
        schema:
          type: string
    post:
      tags:
        - Educational Videos
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: postVideo
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
              example:
                Status: 0
                response: No token provided
    put:
      tags:
        - Educational Videos
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: putVideo
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Server Not Working
  '/video/{id}':
    parameters:
      - name: Get server health status
        in: query
        description: status response
        schema:
          type: string
    delete:
      tags:
        - Educational Videos
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteVideo
      parameters:
        - name: id
          in: path
          description: The name that needs to be fetched
          required: true
          schema:
            type: string
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
              example:
                Status: ONLINE
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
              example:
                Status: ONLINE
components:
  schemas:
    Admin:
      type: object
      properties:
        email:
          $ref: '#/components/schemas/Email'
        password:
          $ref: '#/components/schemas/Password'
        lastLogin:
          type: string
          format: date-time
    Appointment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: NUMBER
        title:
          description: User supplied username
          type: string
          minLength: 4
          example: hemprasad
        agenda:
          description: User supplied username
          type: string
          minLength: 4
          example: hemprasad
        patient:
          description: User supplied username
          type: string
          minLength: 4
          example: hemprasad
        doctor:
          description: User supplied username
          type: string
          minLength: 4
          example: hemprasad
        date:
          description: User supplied username
          type: string
          minLength: 4
          example: hemprasad
        startTime:
          type: string
          format: date-time
          description: GILT_AB of first CW_STUNDENPLAN
        endTime:
          type: string
          format: date-time
          description: GILT_AB of first CW_STUNDENPLAN
        reminderEmail:
          $ref: '#/components/schemas/Email'
        confirmedByDoctor:
          type: boolean
          description: CW_KALENDER.DEAKTIVIERT
          default: false
        confirmedByPatient:
          type: boolean
          description: CW_KALENDER.DEAKTIVIERT
          default: false
        status:
          type: string
          description: 'State of the appointment: booked, cancelled, ...'
    Degree:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Degree ID
        name:
          type: string
          description: Name of Degree
        year:
          type: string
          format: date
          description: year
    Doctor:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: PATIENTID
        person:
          $ref: '#/components/schemas/Person'
        degree:
          type: array
          description: Degrees of Doctor
          items:
            $ref: '#/components/schemas/Degree'
        speciality:
          type: array
          description: Specialities of Doctor
          items:
            $ref: '#/components/schemas/Speciality'
        experience:
          type: integer
          format: int64
          description: VORNAME
        affiliation:
          type: string
          description: 'Doctor Affiliation with Institutes / Hospitals '
      description: doctor
    Email:
      description: User email address
      type: string
      format: test
      example: hemprasad.badgujar@columbusx.com
    Image:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Image ID
        title:
          type: string
          description: Name of Image
        link:
          type: string
          format: uri
          description: link of Image
    Password:
      description: User password
      type: string
      format: password
      example: hemprasad.badgujar@columbusx.com
    Patient:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: PATIENTID
        person:
          $ref: '#/components/schemas/Person'
      description: Patient
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: PERSNR
        firstname:
          type: string
          description: VORNAME
        lastname:
          type: string
          description: NAME
        gender:
          type: integer
          format: int64
          description: 'SEX, gender/sex'
        phone:
          type: integer
          format: int64
          description: PERSNR
        address:
          type: string
          description: ''
        profileImage:
          type: string
          description: VORNAME
        userType:
          type: string
          default: patient
        lastLogin:
          type: string
          format: date-time
        isLogin:
          type: boolean
          default: false
        isConfirmed:
          type: boolean
          default: true
      description: NATPERSON
    Speciality:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Speciality
        name:
          type: string
          description: VORNAME
    Status:
      description: Server Status
      type: string
      format: test
      example:
        status: ONLINE
    User:
      type: object
      properties:
        username:
          description: User supplied username
          type: string
          minLength: 4
          example: hemprasad
        firstName:
          description: User first name
          type: string
          minLength: 1
          example: hemprasad
        lastName:
          description: User last name
          type: string
          minLength: 1
          example: badgujar
        email:
          $ref: '#/components/schemas/Email'
    Video:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Video ID
        title:
          type: string
          description: Name of Video
        link:
          type: string
          format: uri
          description: link of Video
  headers:
    ExpiresAfter:
      description: date in UTC when token expires
      schema:
        type: string
        format: date-time
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://seers.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://example.com/oauth/authorize'
          tokenUrl: 'https://example.com/oauth/token'
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations
    OpenID:
      type: openIdConnect
      openIdConnectUrl: 'https://example.com/.well-known/openid-configuration'
